- hosts: all
  become: true
  tasks:
    # сгенерируем файл конфигурации на основе шаблона
    # и укажем, что требуется выполнить задачу “restart sshd”
    # если файл изменился
  - name: write the sshd config file
    template: src=templates/ssh_config.j2 dest=/etc/ssh/ssh_config
    notify:
    - restart sshd

  - name: ensure sshd is running
    service: name=sshd state=started
    # Create sources.list file
  - name: write sources.list file
    template: src=templates/sources.list dest=/etc/apt/sources.list
    # Add Github to known_hosts properly and securely
  - name: ensure github.com is a known host  
    lineinfile:
      dest: /root/.ssh/known_hosts
      create: yes
      state: present
      line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
      regexp: "^github\\.com"
  - apt: name=git state=installed
    become: yes
  - name: Checkout ansible–playground repository
    git: repo=https://github.com/PhilippMorris/Ansible.git dest=~/checkout
    become: yes


  
  handlers:
    - name: restart sshd
      # используем модуль service для перезапуска
      service: name=sshd state=restarted