---
- apt_repository:
    repo: 'ppa:fkrull/deadsnakes'
- name: Update repositories cache and install python 2.7.12
  apt:
    name: python2.7
    update_cache: yes
- name: install python pip
  pip:
    name: pip
    state: latest
- name: remove azure pip packages
  pip:
    name: "{{ item }}"
    state: absent
  with_items:
    - azure
    - azure-mgmt
    - azure-mgmt-authorization
    - azure-mgmt-cdn
    - azure-mgmt-compute
    - azure-mgmt-dns
    - azure-mgmt-logic
    - azure-mgmt-graphrbac
    - azure-mgmt-network
    - azure-mgmt-notificationhubs
    - azure-mgmt-redis
    - azure-mgmt-resource
    - azure-mgmt-scheduler
    - azure-mgmt-storage
    - azure-mgmt-web
    - azure-mgmt-nspkg
    - azure-graphrbac
    - azure-servicebus
    - azure-storage
    - azure-common
    - azure-nspkg
- name: install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - urllib3[secure]
    - cheetah
    - configparser
    - distribute
    - geopy
    - geoip2
    - httplib2
    - Jinja2
    - paramiko
    - pymongo
    - pytz
#    - python-apt
    - python-debian
    - pyyaml
    - requests
    - sendgrid
    - setuptools
    - sh
    - six
    - untangle
    - azure-servicebus