- name: Install libpam-google-authenticator
  apt: 
    name: libpam-google-authenticator 
    state: latest
- name: check if directory .ssh exists
  file: 
    path: /home/acadmin/.ssh/
    recurse: yes
    state: directory
- name: copy sshd config
  copy: 
    src: files/ssh
    dest: /etc/pam.d/
    owner: root
    group: root
    mode: 0644
- name: copy pam config
  copy: 
    src: files/ssh/authorized_keys
    dest: /home/acadmin/.ssh/authorized_keys
    owner: acadmin
    group: acadmin
    mode: 0400
- name: copy pam config
  copy: 
    src: files/ssh/google_authenticator
    dest: /home/acadmin/.google_authenticator
    owner: acadmin
    group: acadmin
    mode: 0400