---
- name: copy detectproxy script
  copy:
    src: files/detectproxy.py
    dest: /opt/detectproxy.py
    owner: root
    group: root
    mode: 0644
- name: run detectproxy script
  command: "/usr/bin/python /opt/detectproxy.py seeder.basechord.com 5001"
- name: add cron job Detect Apt Proxy
  cron:
    name: Detect Apt Proxy
    month: "*"
    weekday: "*"
    hour: "*"
    minute: "15"
    job: /usr/bin/python /opt/detectproxy.py seeder.basechord.com 5001