---
- name: SymlinkWinPe
  command: /opt/stationcontent/symlinkcontent.py --targetdir /usr/share/pxe/winpe --contentfilter winpe*
  listen: Symlink
- name: SymlinkClonezilla
  command: /opt/stationcontent/symlinkcontent.py --targetdir /usr/share/pxe/clonezilla --contentfilter clonezilla*
  listen: Symlink
- name: check tftpd-hpa running
  service: name=tftpd-hpa state=started enabled=yes